# Site settings
title: NikolSpencer		
email: nikolspencer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Front end development, design and random musings
baseurl: "" # the subpath of your site, e.g. /blog/
url: # the base hostname & protocol for your site
twitter_username: nikolspencer
github_username:  nikolspencer

# Build settings
markdown: kramdown
highlighter: pygments

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Collections
collections:
    portfolio:
    output: true
    permalink: /portfolio/:path/
