# Site settings
title: NikolSpencer		
email: nikolspencer@gmail.com
author: Nikki Spencer
description: "Front end development, design and random musings"
baseurl: "" 
url: "wearemavin.github.io"
date_format: "%B %-d, %Y"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5

# Collections
collections:
    portfolio:
    output: true
    permalink: /portfolio/:path/
